### ISSUE TITLE
Afloat freezes every app that it injects into

### ISSUE THREAD

**Issue by saagarjha** [w0lfschild/afloat#1]
Yesterday, after updating to 10.12.3 Beta (16D25a), I was hit by a nasty bug that caused Afloat to hang apps that it would try to inject into. Opening "injectable" apps such as mySIMBL, Terminal, Activity Monitor, etc. would cause them to freeze instantly. Apps that Afloat could not inject into were not affected (i.e. Safari).

**Comment by w0lfschild** [comment]
I'm not having this issue. Maybe it's another plugin or a conflict or something?

Do they actually crash or just hang?

**Comment by saagarjha** [comment]
Looks like I was using an out of date version–2.5.2 seems to work fine (though I wouldn't know why…it doesn't look like there's a whole lot of changes).

**Comment by saagarjha** [comment]
Looks like I spoke too soon. The behavior is better now, but it's still freezing some things; in particular Activity Monitor opens and is responsive, but no data shows up, Terminal and iTerm 2 don't even get a window open, and running top/htop in xterm makes the window unclosable.

**Comment by saagarjha** [comment]
I haven't seen this in a while, so I'll close this.
